### ISSUE TITLE
Reddit and Soundcloud Not Working

### ISSUE THREAD

**Issue by zgtibu** [SergheiPogor/AMF#1]
Reddit and Soundcloud Not Working. It is just refreshing main page.

**Comment by SergiuPogor** [comment]
try to logout and then login back for both, reddit and SoundCloud accounts.

**Comment by zgtibu** [comment]
instagram and facebook likes and followers not working

**Comment by SergiuPogorDev** [comment]
**Checkout latest release v1.0.2 from July 05, 2022**

Please read careful README file before updating/using the script
This issue will be closed, if you get any other new issues, try steps from README.
If still not helping, open a new issue on GitHub with details(including steps to recreate the issue)
