### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by nrytex** [SergheiPogor/AMF#10]
Unchecked runtime.lastError: The message port closed before a response was received.

**Comment by wukaixiang** [comment]
Unchecked runtime.lastError: The message port closed before a response was received.

**Comment by wukaixiang** [comment]
Can only open the window, but can not automatically complete

**Comment by nrytex** [comment]
youtube can not automatically complete

**Comment by SergiuPogor** [comment]
will last update should be fixed
