### ISSUE TITLE
Facebook Like / Instagram Like-Follow / Reddit / Is Not working. Fix Please

### ISSUE THREAD

**Issue by gs727msuw72** [SergheiPogor/AMF#5]

**Comment by ibHans** [comment]
fb/ig/twitter/yt. button click command not working properly.

**Comment by SergiuPogorDev** [comment]
**Checkout latest release v1.0.2 from July 05, 2022**

Please read the careful README file before updating/using the script
This issue will be closed, if you get any other new issues, try steps from README.
If still not helping, open a new issue on GitHub with details(including steps to recreate the issue)
