### ISSUE TITLE
cant download 

### ISSUE THREAD

**Issue by meleduk** [SergheiPogor/AMF#8]
hi sir.

cant download always show error,

**Comment by SergiuPogorDev** [comment]
not sure if I understand you, you can't download the repo?
just click **Download Zip** 

... but I strongly suggest you to use GIT commands, not just downloading
- git clone https://github.com/SergheiPogor/AMF.git


![Screenshot from 2022-08-09 08-44-32](https://user-images.githubusercontent.com/79079906/183573591-48be5240-0af0-4590-9b43-928cf195aab8.png)
