### ISSUE TITLE
youtube not working. reddit not working. IG not working some click follow 

### ISSUE THREAD

**Issue by ROBOTOXIC999** [SergheiPogor/AMF#9]

**Comment by SergiuPogorDev** [comment]
The latest test on 15 Aug 2022

 + YouTube Subscribe -> **Work**
 + YouTube Like -> **Work**
 
 + Reddit Follow -> **Work**
 + Reddit Like -> **Work**
  
 Everything works fine and there is no issue with the extension.
 *** if bot execute needed action but AddMeFAst doesn't count that action then it's NOT A BOT ISSUE**
 
 Please read **README** file for more details and possible solutions to fix your issues
